---
- name: Exchange Keys between servers
  become: yes
  become_user: samir
  hosts: all
  tasks:
    - name: SSH KeyGen command
      shell: >
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"

    - name: Fetch the keyfile from one server to another
      fetch:
        src: "~/.ssh/id_rsa.pub"
        dest: "buffer/{{ansible_hostname}}-id_rsa.pub"
        flat: yes


    - name: add the public key into Authorized_keys file to enable Key Auth
      shell: "cat ~/.ssh/id_rsa >> ~/.ssh/authorized_keys"
      register: addtoauth