---
- name: Exchange Keys between servers
  become: yes
  hosts: all
  tasks:

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ssh_keys/
        dest: ~/.ssh/ssh_keys/
        remote_src: yes
        directory_mode: yes

    - name: add the public key into Authorized_keys file to enable Key Auth
      shell: "cat ~/.ssh/ssh_keys/* > ~/.ssh/authorized_keys"