---
- name: Deploy a web application
  hosts: all
  become: yes

  tasks:

  - name: Install dependencies
    apt:
      name: [ "doker.io", "supervisor"]
      update_cache: true
      state: latest