---
- name: Deploy a web application
  hosts: all
  become: yes

  tasks:

  - name: Install dependencies
    apt:
      name: [ "ca-certificates", "curl", "gnupg", "lsb-release"]
      update_cache: true
      state: latest

