---
- name: Deploy a web application
  hosts: all
  become: yes

  tasks:

  - name: Install a .deb package
  apt:
    deb: https://download.docker.com/linux/ubuntu/dists/artful/pool/stable/amd64/docker-ce_18.06.3~ce~3-0~ubuntu_amd64.deb