---

- name: Install java
  apt:
    name: openjdk-11-jdk
    state: latest

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: Add Jenkins repository
  command: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: Install jenkins
  apt:
    name: jenkins
    update_cache: yes

- name: cat file
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: cat_content_file

- name: echo file
  debug:
    msg: "{{ cat_content_file.stdout }}"